/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Faxes {
  codigo_fax: Generated<number>;
  creado_el: Date;
  nombre_fax: string;
}

export interface DB {
  faxes: Faxes;
}
