/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Faxes {
  creado_el: string;
  id: string;
  numero_fax: string;
}

export interface DB {
  faxes: Faxes;
}
